import { Treatment } from "@/types";

export const TREATMENTS_FALLBACK: Treatment[] = [
  {
    id: "1",
    slug: "brackets-metalicos",
    nombre: "Ortodoncia",
    categoria: "ortodoncia",
    descripcion_corta: "Corregimos la posición de tus dientes para mejorar tanto la estética como la funcionalidad de tu boca. Con brackets tradicionales.",
    descripcion_larga: "Corregir la posición de los dientes no es solo una cuestión estética. A veces cuesta masticar bien, otras aparecen desgastes, y en muchos casos, simplemente no estás a gusto con tu sonrisa. En La Fábrica de Sonrisas estudiamos cada caso de forma individual y buscamos la solución que mejor se adapte a ti.\n\nOfrecemos ortodoncia con alineadores invisibles, brackets metálicos y sistemas como Damon (autoligado), además de tratamientos más complejos como disyunción del paladar o microimplantes cuando es necesario. Usamos escáner intraoral para evitar las molestas pastas que tanto incomodan a algunos pacientes.\n\nTodo se planifica desde el inicio. Te explicamos cada paso. Hacemos un seguimiento continuo y ajustamos lo necesario para que el tratamiento sea cómodo, eficaz y dé resultados duraderos.",
    para_quien: "Para adolescentes y adultos que quieren corregir la posición de sus dientes, mejorar la mordida o recuperar la comodidad al masticar.",
    duracion: "12–24 meses",
    precio_min: 1800, precio_max: 3200, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 10, updated_at: "",
    imagen_url: "https://www.lafabricadesonrisasgranada.com/wp-content/uploads/ortodoncia-en-granada.webp",
    imagen2_url: "https://www.lafabricadesonrisasgranada.com/wp-content/uploads/ortodoncia-lfds.webp",
    faq: [
      { pregunta: "¿Duele ponerse los brackets?", respuesta: "Los brackets no duelen al colocarlos. Los primeros días notas presión y algo de molestia, que desaparece con un analgésico suave." },
      { pregunta: "¿Puedo comer de todo?", respuesta: "Mejor evitar alimentos muy duros o pegajosos. El resto, sin problema." },
      { pregunta: "¿Usáis escáner intraoral?", respuesta: "Sí, usamos escáner intraoral para evitar las molestas pastas de impresión tradicionales." },
    ],
  },
  {
    id: "2",
    slug: "ortodoncia-invisible",
    nombre: "Ortodoncia invisible",
    categoria: "ortodoncia",
    descripcion_corta: "Una opción discreta y cómoda. Alineadores transparentes que corrigen tu sonrisa sin que apenas se note.",
    descripcion_larga: "¿Brackets? ¿Hierros en la boca? ¡No, gracias! En La Fábrica de Sonrisas tenemos una solución mágica (bueno, casi): la ortodoncia invisible. Es como tener superpoderes dentales… pero sin que nadie lo note. Puedes corregir tu sonrisa mientras sigues comiendo palomitas en el cine (con cuidado, ¿eh?) y haciendo selfies sin parecer un Transformer.\n\nNuestros alineadores son tan discretos que ni tu madre se dará cuenta. Y lo mejor: son cómodos, removibles y personalizados para ti. Porque cada sonrisa es única, como tú (sí, aunque tengas ese diente rebelde que va por libre).\n\nAsí que, si quieres alinear tus dientes sin dramas ni looks metálicos, ven a vernos. En La Fábrica de Sonrisas, hacemos magia… pero con odontología.",
    para_quien: "Para quien quiere discreción total. Especialmente popular entre adultos y profesionales que no quieren que se note que llevan ortodoncia.",
    duracion: "6–18 meses",
    precio_min: 2500, precio_max: 4500, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 11, updated_at: "",
    imagen_url: "https://www.lafabricadesonrisasgranada.com/wp-content/uploads/ortodoncia-invisible-lfds.webp",
    imagen2_url: "https://www.lafabricadesonrisasgranada.com/wp-content/uploads/La-Fabrica-de-Sonrisas-bodegon-2.webp",
    faq: [
      { pregunta: "¿Es tan eficaz como los brackets?", respuesta: "Para casos leves y moderados, la eficacia es comparable. Para casos complejos, lo valoramos juntos en la primera visita." },
      { pregunta: "¿Hay que llevarlos todo el día?", respuesta: "Se recomiendan 20–22 horas diarias. Se retiran solo para comer y cepillarse." },
      { pregunta: "¿Puedo ver el resultado antes de empezar?", respuesta: "Sí, con la planificación digital puedes ver una simulación del resultado final antes de tomar ninguna decisión." },
    ],
  },
  {
    id: "3",
    slug: "implante-unitario",
    nombre: "Implantología",
    categoria: "implantes",
    descripcion_corta: "Recupera tus dientes perdidos con implantes dentales seguros, estables y con un aspecto natural. Para volver a sonreír sin preocuparte.",
    descripcion_larga: "En La Fábrica de Sonrisas, ayudamos a recuperar sonrisas con implantes dentales diseñados para ofrecerte comodidad, seguridad y resultados duraderos. Sabemos que perder una pieza dental puede afectar tanto a la función como a la confianza, por eso trabajamos con soluciones que reemplazan el diente perdido de forma natural y totalmente funcional.\n\nLos implantes son pequeñas estructuras de titanio que se colocan en el hueso maxilar o mandibular para sustituir la raíz del diente original. Sobre ellos se fija una corona personalizada que imita el color, la forma y el brillo del resto de tus dientes, logrando un resultado completamente estético y estable.\n\nEn nuestra clínica, cada tratamiento se planifica de manera individual, utilizando materiales de alta calidad y las técnicas quirúrgicas más seguras. El objetivo es claro: que recuperes tu sonrisa sin molestias, con la tranquilidad de estar en manos expertas.\n\nDesde la primera consulta, te explicamos cada paso del proceso con transparencia y cercanía, acompañándote antes, durante y después del tratamiento. Porque queremos que te sientas cómodo y con confianza de nuevo al sonreír.",
    para_quien: "Para cualquier persona que haya perdido una o varias piezas dentales y quiera una solución fija, estética y duradera.",
    duracion: "3–6 meses (incluye cicatrización)",
    precio_min: 1200, precio_max: 2000, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 20, updated_at: "",
    imagen_url: "https://www.lafabricadesonrisasgranada.com/wp-content/uploads/implantes-dentales-en-granada.webp",
    imagen2_url: "https://www.lafabricadesonrisasgranada.com/wp-content/uploads/beneficios-de-los-implantes-dentales-en-granada.webp",
    faq: [
      { pregunta: "¿Duele la operación?", respuesta: "Se realiza con anestesia local. Durante la intervención no sientes dolor. Después puede haber algo de molestia los primeros días, que se controla fácilmente con medicación." },
      { pregunta: "¿Cuánto dura un implante?", respuesta: "Con una buena higiene y revisiones periódicas, un implante puede durar décadas o toda la vida." },
      { pregunta: "¿Cuánto tiempo tarda el proceso completo?", respuesta: "En general entre 3 y 6 meses, incluyendo el tiempo de cicatrización del hueso antes de colocar la corona definitiva." },
    ],
  },
  {
    id: "4",
    slug: "implantes-multiples",
    nombre: "Implantes múltiples",
    categoria: "implantes",
    descripcion_corta: "Cuando necesitas reponer varias piezas, los implantes múltiples son la solución más estable y natural.",
    descripcion_larga: "Si has perdido varios dientes, podemos valorar diferentes soluciones: implantes individuales para cada pieza, o estructuras que se apoyan en menos implantes (puentes sobre implantes). Cada caso se estudia individualmente para encontrar la opción más eficaz y económica.",
    para_quien: "Para quienes han perdido varios dientes y quieren una solución fija y duradera.",
    duracion: "Según planificación individual",
    precio_min: 2500, precio_max: 6000, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 21, updated_at: "",
    imagen_url: "https://www.lafabricadesonrisasgranada.com/wp-content/uploads/implantes-dentales-granada.webp",
    faq: [],
  },
  {
    id: "5",
    slug: "blanqueamiento-dental",
    nombre: "Estética dental",
    categoria: "estetica",
    descripcion_corta: "Mejoramos el aspecto de tu sonrisa con un enfoque natural, armónico y hecho a tu medida.",
    descripcion_larga: "En La Fábrica de Sonrisas, entendemos que mejorar tu sonrisa no es únicamente un tratamiento dental: es una experiencia personal que influye en tu autoestima, en cómo te relacionas y en cómo te ves cada día frente al espejo. Por eso, trabajamos la estética dental desde un enfoque cercano, respetuoso y totalmente adaptado a ti, buscando siempre un equilibrio real entre forma, color y expresión facial.\n\nNuestro objetivo es embellecer tu sonrisa manteniendo intacta su funcionalidad, para que puedas seguir hablando, riendo y comiendo con la misma comodidad de siempre, pero con un aspecto mucho más armonioso. Para conseguirlo, realizamos un estudio previo muy cuidadoso y utilizamos tecnología digital en 3D, que nos permite mostrarte una simulación del resultado antes de comenzar el tratamiento. Así, tomas decisiones con tranquilidad, sabiendo exactamente hacia dónde avanzamos.\n\nYa busques un cambio sutil o una transformación más visible, diseñamos un plan específico para ti, combinando las técnicas de estética dental que mejor encajan con tus objetivos y con la anatomía natural de tus dientes.",
    para_quien: "Para quien quiere mejorar el aspecto de su sonrisa, ya sea un cambio sutil de color o una transformación más completa.",
    duracion: "1 sesión (blanqueamiento) o 2–3 sesiones (carillas)",
    precio_min: 200, precio_max: 400, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 30, updated_at: "",
    imagen_url: "https://www.lafabricadesonrisasgranada.com/wp-content/uploads/estetica-dental.webp",
    imagen2_url: "https://www.lafabricadesonrisasgranada.com/wp-content/uploads/La-Fabrica-de-Sonrisas-bodegon-1.webp",
    faq: [
      { pregunta: "¿Puedo ver el resultado antes de empezar?", respuesta: "Sí, usamos tecnología digital en 3D para mostrarte una simulación del resultado antes de tomar ninguna decisión." },
      { pregunta: "¿El blanqueamiento daña el esmalte?", respuesta: "El blanqueamiento profesional, bien indicado, no daña el esmalte." },
      { pregunta: "¿Las carillas son para siempre?", respuesta: "Las carillas de porcelana son una solución muy duradera. Con un buen cuidado pueden durar muchos años." },
    ],
  },
  {
    id: "6",
    slug: "carillas-porcelana",
    nombre: "Carillas de porcelana",
    categoria: "estetica",
    descripcion_corta: "Transforma tu sonrisa de forma permanente con carillas ultrafinas de porcelana.",
    descripcion_larga: "Las carillas son láminas muy finas de porcelana que se adhieren a la cara visible del diente. Corrigen el color, la forma, el tamaño y pequeñas posiciones, con un resultado completamente natural y duradero.",
    para_quien: "Para quien quiere un cambio estético significativo y duradero en su sonrisa.",
    duracion: "2–3 sesiones",
    precio_min: 600, precio_max: 1200, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 31, updated_at: "",
    imagen_url: "https://www.lafabricadesonrisasgranada.com/wp-content/uploads/estetica-dental.webp",
    faq: [],
  },
  {
    id: "7",
    slug: "composite-estetico",
    nombre: "Composite estético",
    categoria: "estetica",
    descripcion_corta: "Mejora tu sonrisa sin tocar el diente: el composite se aplica directamente sobre el esmalte.",
    descripcion_larga: "El composite es una resina de alta estética que el odontólogo modela directamente sobre el diente, sin necesidad de tallado ni laboratorio. Es reversible, rápido y muy económico para correcciones puntuales.",
    para_quien: "Ideal para corregir pequeñas fracturas, dientes separados o irregularidades leves.",
    duracion: "1 sesión por diente",
    precio_min: 150, precio_max: 350, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 32, updated_at: "", faq: [],
  },
  {
    id: "8",
    slug: "tratamiento-periodontal",
    nombre: "Periodoncia",
    categoria: "periodoncia",
    descripcion_corta: "Tratamos las enfermedades de las encías antes de que dañen tu sonrisa. Porque unas encías sanas son clave para mantener tus dientes.",
    descripcion_larga: "En La Fábrica de Sonrisas abordamos la periodoncia como un tratamiento fundamental para mantener la salud bucodental a largo plazo. La enfermedad periodontal, conocida comúnmente como periodontitis o "piorrea", es una patología frecuente que afecta a las encías y al hueso que sostiene los dientes, y que en muchos casos avanza sin causar dolor evidente en sus fases iniciales.\n\nSe trata de una enfermedad crónica que, si no se trata de forma adecuada, puede provocar la pérdida progresiva del soporte dental. Las bacterias presentes en la placa y el sarro son las responsables de esta inflamación, por lo que un diagnóstico temprano y un tratamiento profesional resultan clave para frenar su avance.\n\nSíntomas como sangrado al cepillado, inflamación de encías, movilidad dental o sensación de que los dientes \"se ven más largos\" no deben normalizarse. Las encías sanas no sangran, y ante cualquier señal de alerta es importante acudir a un profesional especializado.\n\nRealizar un tratamiento de periodoncia de forma adecuada aporta beneficios claros: frena el avance de la infección, conserva las piezas dentales, mejora el aspecto de las encías y previene complicaciones más graves en el futuro. En La Fábrica de Sonrisas trabajamos con un enfoque profesional y cercano, explicando cada paso del tratamiento para que te sientas seguro y acompañado.",
    para_quien: "Para quienes presentan sangrado al cepillado, encías inflamadas o retraídas, movilidad dental o sensación de que los dientes se ven más largos. También como mantenimiento preventivo.",
    duracion: "2–4 sesiones según severidad",
    precio_min: 200, precio_max: 600, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 40, updated_at: "",
    imagen_url: "https://www.lafabricadesonrisasgranada.com/wp-content/uploads/periododncia-lfds.webp",
    imagen2_url: "https://www.lafabricadesonrisasgranada.com/wp-content/uploads/periodoncia-en-granada.webp",
    faq: [
      { pregunta: "¿La periodontitis tiene cura?", respuesta: "Es una enfermedad crónica, pero con tratamiento adecuado y mantenimiento se puede controlar completamente y conservar los dientes a largo plazo." },
      { pregunta: "¿Las encías sanas sangran?", respuesta: "No. El sangrado al cepillarse es siempre una señal de alerta. Si te ocurre, consúltanos." },
      { pregunta: "¿Duele el tratamiento periodontal?", respuesta: "Se realiza con anestesia local. La mayoría de pacientes lo describe como perfectamente tolerable." },
    ],
  },
  {
    id: "9",
    slug: "extraccion-muela-juicio",
    nombre: "Extracción de muela del juicio",
    categoria: "cirugia",
    descripcion_corta: "Cuando no queda otra opción, realizamos extracciones dentales seguras y con el menor impacto posible. Siempre con todas las garantías.",
    descripcion_larga: "Las muelas del juicio frecuentemente no tienen espacio para erupcionar correctamente, causando dolor, infecciones y daño a dientes vecinos. Se realiza bajo anestesia local.",
    para_quien: "Para quien tiene las muelas del juicio retenidas, semi-incluidas o que causan molestias.",
    duracion: "30–60 min por pieza",
    precio_min: 180, precio_max: 400, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 50, updated_at: "", faq: [],
  },
  {
    id: "10",
    slug: "cirugia-osea",
    nombre: "Cirugía de regeneración ósea",
    categoria: "cirugia",
    descripcion_corta: "Recuperamos el hueso perdido para que los implantes tengan la base que necesitan.",
    descripcion_larga: "Cuando hay pérdida de hueso, puede ser necesario regenerarlo antes de colocar implantes. Se utilizan membranas y materiales de relleno que estimulan la formación de nuevo hueso.",
    para_quien: "Indicado como paso previo a la implantología en casos con deficiencia ósea.",
    duracion: "Según extensión de la zona",
    precio_min: 400, precio_max: 1200, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 51, updated_at: "", faq: [],
  },
  {
    id: "11",
    slug: "revision-diagnostico",
    nombre: "Odontología general",
    categoria: "general",
    descripcion_corta: "Revisiones, higiene bucodental y tratamientos restauradores para mantener tu boca sana día a día. Es la base de todo buen cuidado dental.",
    descripcion_larga: "La odontología general, también conocida como restauradora, es la encargada de solucionar uno de los problemas de salud más comunes y principal motivo de asistencia a una clínica dental: la caries. Se trata de la enfermedad infecciosa de mayor prevalencia en el género humano, produciendo la lesión de los tejidos del diente (esmalte, dentina y cemento) por medio de bacterias que acidifican el medio bucal.\n\nSe soluciona con tratamientos restauradores como la obturación (empaste) o reconstrucción. Si no se trata a tiempo, puede alcanzar los vasos y nervios de la pulpa. Cuando esto sucede origina dolor, infección e impotencia funcional, y hay que pasar al plan B (endodoncia).\n\nEn La Fábrica no hacemos endodoncias, pero colaboramos con un especialista de contrastada experiencia, que será quien lleve a cabo dicho tratamiento en su clínica de Granada.",
    para_quien: "Para cualquier persona con caries, obturaciones antiguas en mal estado, o que simplemente quiera una revisión completa de su boca. Primera visita gratuita.",
    duracion: "30–60 minutos",
    precio_min: 0, precio_max: 0, unidad: "sesion",
    es_precio_real: false, visible: true, orden: 61, updated_at: "",
    imagen_url: "https://www.lafabricadesonrisasgranada.com/wp-content/uploads/odontologia-general-lfds.webp",
    faq: [
      { pregunta: "¿La primera visita es gratuita?", respuesta: "Sí, la primera visita de valoración es sin coste y sin compromiso." },
      { pregunta: "¿Hacéis endodoncias en la clínica?", respuesta: "No realizamos endodoncias, pero contamos con un especialista de contrastada experiencia con quien colaboramos y que llevará a cabo el tratamiento si fuera necesario." },
      { pregunta: "¿Cómo sé si tengo caries?", respuesta: "La caries no siempre duele en sus primeras fases. Una revisión periódica es la mejor forma de detectarla a tiempo y evitar tratamientos más complejos." },
    ],
  },
  {
    id: "12",
    slug: "limpieza-bucal",
    nombre: "Limpieza dental profesional",
    categoria: "general",
    descripcion_corta: "La limpieza que marca la diferencia. Eliminamos el sarro y dejamos tu boca a punto.",
    descripcion_larga: "La limpieza profesional elimina el sarro y la placa que el cepillo no alcanza. También incluye pulido dental y fluorización si se indica. Se recomienda al menos una vez al año.",
    para_quien: "Para todo el mundo como mantenimiento preventivo.",
    duracion: "45–60 minutos",
    precio_min: 50, precio_max: 80, unidad: "sesion",
    es_precio_real: false, visible: true, orden: 62, updated_at: "",
    faq: [{ pregunta: "¿Con qué frecuencia debo hacerme una limpieza?", respuesta: "La recomendación general es una vez al año, o cada 6 meses si hay antecedentes de periodontitis." }],
  },
  {
    id: "13",
    slug: "empaste",
    nombre: "Empaste dental (composite)",
    categoria: "general",
    descripcion_corta: "Tratamos la caries y restauramos el diente con composite del color exacto de tus dientes.",
    descripcion_larga: "Cuando hay caries, extraemos el tejido dañado y rellenamos el espacio con un composite del color de tus dientes. El resultado es invisible, resistente y se termina en una sola visita.",
    para_quien: "Para cualquier persona con caries diagnosticada, de cualquier tamaño.",
    duracion: "30–60 minutos",
    precio_min: 50, precio_max: 120, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 63, updated_at: "",
    faq: [{ pregunta: "¿Se nota el empaste?", respuesta: "Con los composites actuales, el empaste queda del color exacto de tu diente." }],
  },
  {
    id: "14",
    slug: "endodoncia",
    nombre: "Endodoncia (tratamiento de conductos)",
    categoria: "general",
    descripcion_corta: "Salvamos el diente cuando la caries o una infección han llegado hasta el nervio.",
    descripcion_larga: "La endodoncia consiste en limpiar el interior del diente y sellarlo para evitar reinfecciones. Permite conservar el diente en la boca. Con la anestesia actual es un procedimiento cómodo.",
    para_quien: "Cuando hay infección profunda, dolor espontáneo nocturno o absceso dental.",
    duracion: "1–3 sesiones",
    precio_min: 200, precio_max: 450, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 64, updated_at: "", faq: [],
  },
  {
    id: "15",
    slug: "corona-dental",
    nombre: "Corona dental",
    categoria: "general",
    descripcion_corta: "Una funda que reconstruye y protege un diente muy dañado, devolviéndole función y estética.",
    descripcion_larga: "Una corona es una funda de cerámica que cubre completamente el diente para protegerlo cuando está muy desgastado, ha sufrido una endodoncia o está muy dañado por caries.",
    para_quien: "Para dientes fracturados, muy desgastados o tratados de endodoncia.",
    duracion: "2–3 sesiones",
    precio_min: 500, precio_max: 950, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 65, updated_at: "", faq: [],
  },
  {
    id: "16",
    slug: "revision-infantil",
    nombre: "Revisión infantil",
    categoria: "odontopediatria",
    descripcion_corta: "La primera visita de los peques: sin miedo, con paciencia y con mucho cariño.",
    descripcion_larga: "Somos especialmente cuidadosas con los más pequeños. La primera visita es siempre de conocernos y explorar sin prisa. Explicamos todo a los niños en su lenguaje.",
    para_quien: "Para niños desde la erupción de los primeros dientes de leche.",
    duracion: "30 minutos",
    precio_min: 0, precio_max: 40, unidad: "sesion",
    es_precio_real: false, visible: true, orden: 70, updated_at: "",
    faq: [{ pregunta: "¿A qué edad debo llevar a mi hijo/a por primera vez?", respuesta: "Recomendamos la primera visita alrededor del año de edad." }],
  },
  {
    id: "17",
    slug: "selladores-fisuras",
    nombre: "Selladores de fisuras",
    categoria: "odontopediatria",
    descripcion_corta: "Protección preventiva para los dientes definitivos de los niños: evitamos la caries antes de que llegue.",
    descripcion_larga: "Los selladores son una resina que se aplica en las fisuras de los molares definitivos recién erupcionados. Es un procedimiento rápido, sin anestesia y muy eficaz para prevenir caries.",
    para_quien: "Para niños de 6–12 años con molares definitivos recién erupcionados.",
    duracion: "15–20 min por cuadrante",
    precio_min: 30, precio_max: 60, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 71, updated_at: "", faq: [],
  },
  {
    id: "18",
    slug: "ortodoncia-infantil",
    nombre: "Ortodoncia interceptiva infantil",
    categoria: "odontopediatria",
    descripcion_corta: "Corregimos a tiempo los problemas que, si se tratan pronto, se resuelven con mucha más facilidad.",
    descripcion_larga: "La ortodoncia interceptiva actúa sobre la mandíbula y los maxilares en crecimiento para corregir discrepancias antes de que se agraven.",
    para_quien: "Para niños entre 6 y 12 años con problemas de mordida, paladar estrecho o apiñamiento severo.",
    duracion: "12–24 meses",
    precio_min: 800, precio_max: 1800, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 72, updated_at: "", faq: [],
  },
  {
    id: "19",
    slug: "autotrasplante-dental",
    nombre: "Autotrasplante dental",
    categoria: "implantes",
    descripcion_corta: "Utilizamos una pieza dental tuya para sustituir otra que no puede conservarse. Una solución innovadora y eficaz.",
    descripcion_larga: "El autotrasplante dental consiste en trasladar un diente propio desde su posición original a otra donde se ha perdido o no puede conservarse. Es una alternativa biológica y duradera a los implantes convencionales, especialmente indicada en pacientes jóvenes.",
    para_quien: "Para pacientes con pérdida dental en los que exista un diente donante adecuado, generalmente muelas del juicio.",
    duracion: "Según planificación individual",
    precio_min: 800, precio_max: 1800, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 22, updated_at: "", faq: [],
  },
  {
    id: "20",
    slug: "diseno-digital-sonrisa",
    nombre: "Diseño Digital de la Sonrisa (DSD)",
    categoria: "estetica",
    descripcion_corta: "Planificamos tu sonrisa ideal de forma digital antes del tratamiento. Así puedes ver el resultado antes de tomar la decisión.",
    descripcion_larga: "El concepto de diseño digital en odontología nació de la necesidad de abordar los desafíos a los que nos enfrentamos los dentistas actuales: fabricar sonrisas naturalmente estéticas dentro de una visión integral, con la mayor precisión que existe actualmente.\n\nEn La Fábrica somos especialistas en Diseño Digital de la Sonrisa (DSD), metodología desarrollada e impulsada por el Dr. Christian Coachman. Disponemos de un escáner intraoral, indispensable para esta nueva forma de entender la odontología. Esta novedosa herramienta permite que el paciente pueda ver su sonrisa ideal — el resultado final — antes incluso de comenzar el tratamiento.\n\nNos permite explicarte con todo lujo de detalles qué procedimientos necesitamos realizar previamente para conseguirla, ya que no consiste exclusivamente en la colocación de carillas estéticas, como erróneamente circula en el imaginario colectivo.\n\nEl futuro es ahora. La odontología digital ha llegado para quedarse, y el Diseño Digital de la Sonrisa para revolucionar esta profesión.",
    para_quien: "Para cualquier persona que quiera mejorar su sonrisa y desee ver el resultado final antes de tomar ninguna decisión ni comprometerse con ningún tratamiento.",
    duracion: "1 sesión de planificación digital",
    precio_min: 0, precio_max: 0, unidad: "sesion",
    es_precio_real: false, visible: true, orden: 33, updated_at: "",
    imagen_url: "https://www.lafabricadesonrisasgranada.com/wp-content/uploads/diseno-de-sonrisas-lfds.webp",
    imagen2_url: "https://www.lafabricadesonrisasgranada.com/wp-content/uploads/La-Fabrica-de-Sonrisas-bodegon-5.webp",
    faq: [
      { pregunta: "¿El DSD es solo para carillas?", respuesta: "No, es un error muy extendido. El DSD es una metodología de planificación completa que puede aplicarse a cualquier tratamiento estético, no únicamente a carillas." },
      { pregunta: "¿Qué es el escáner intraoral?", respuesta: "Es una herramienta digital que obtiene un modelo 3D exacto de tu boca sin necesidad de las incómodas pastas de impresión tradicionales." },
      { pregunta: "¿Puedo ver el resultado antes de empezar?", respuesta: "Sí, precisamente eso es lo más valioso del DSD: puedes ver una simulación de tu sonrisa ideal y aprobarla antes de iniciar cualquier tratamiento." },
    ],
  },
  {
    id: "21",
    slug: "disyuncion-palatina",
    nombre: "Disyunción palatina",
    categoria: "ortodoncia",
    descripcion_corta: "Tratamiento avanzado que corrige la estructura del maxilar para mejorar la respiración, la funcionalidad y la estabilidad de la sonrisa con resultados duraderos.",
    descripcion_larga: "La disyunción palatina es un tratamiento ortodóncico que amplía el paladar mediante un dispositivo expansor. Corrige el paladar estrecho, mejora la respiración nasal y crea espacio para que los dientes se alineen correctamente.",
    para_quien: "Para pacientes con paladar estrecho, respiración bucal o problemas de mordida cruzada posterior.",
    duracion: "3–6 meses",
    precio_min: 800, precio_max: 1500, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 12, updated_at: "", faq: [],
  },
  {
    id: "22",
    slug: "microimplantes-dentales",
    nombre: "Microimplantes dentales",
    categoria: "implantes",
    descripcion_corta: "Soluciones mínimamente invasivas para mejorar la estabilidad de prótesis o sustituir piezas dentales en casos específicos. Comodidad y funcionalidad desde el primer momento.",
    descripcion_larga: "Los microimplantes dentales son pequeños implantes de titanio que se colocan de forma mínimamente invasiva. Se usan como anclaje en ortodoncia o como soporte de prótesis en casos donde los implantes convencionales no son viables.",
    para_quien: "Para pacientes que necesitan anclaje ortodóncico adicional o soporte protésico con poco hueso disponible.",
    duracion: "1 sesión de colocación",
    precio_min: 300, precio_max: 700, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 23, updated_at: "", faq: [],
  },
  {
    id: "23",
    slug: "cirugia-periodontal",
    nombre: "Cirugía periodontal",
    categoria: "periodoncia",
    descripcion_corta: "Tratamientos avanzados para eliminar la infección en las encías y frenar su avance. Protegemos la base de tu sonrisa para mantener tus dientes a largo plazo.",
    descripcion_larga: "La cirugía periodontal se indica cuando el tratamiento no quirúrgico no es suficiente para controlar la enfermedad de las encías. Permite acceder a zonas profundas para eliminar la infección y, en algunos casos, regenerar tejido óseo perdido.",
    para_quien: "Para pacientes con periodontitis avanzada que no responde al tratamiento convencional.",
    duracion: "1–2 sesiones según extensión",
    precio_min: 500, precio_max: 1500, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 41, updated_at: "", faq: [],
  },
];
