import { Treatment } from "@/types";

export const TREATMENTS_FALLBACK: Treatment[] = [
  {
    id: "1",
    slug: "brackets-metalicos",
    nombre: "Ortodoncia con brackets metálicos",
    categoria: "ortodoncia",
    descripcion_corta: "Corregimos la posición de tus dientes para mejorar tanto la estética como la funcionalidad de tu boca. Con brackets tradicionales.",
    descripcion_larga: "Los brackets metálicos son la opción más consolidada en ortodoncia. Hoy son mucho más pequeños, cómodos y eficaces que los de antes. Corrigen desde leves apiñamientos hasta maloclusiones complejas, con resultados predecibles y duraderos.",
    para_quien: "Ideal para adolescentes y adultos que buscan una solución eficaz a un precio equilibrado.",
    duracion: "12–24 meses",
    precio_min: 1800, precio_max: 3200, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 10, updated_at: "",
    faq: [
      { pregunta: "¿Duele ponerse los brackets?", respuesta: "Los brackets no duelen al colocarlos. Los primeros días notas presión y algo de molestia, que desaparece con un analgésico suave." },
      { pregunta: "¿Puedo comer de todo?", respuesta: "Mejor evitar alimentos muy duros o pegajosos. El resto, sin problema." },
    ],
  },
  {
    id: "2",
    slug: "ortodoncia-invisible",
    nombre: "Ortodoncia invisible (alineadores)",
    categoria: "ortodoncia",
    descripcion_corta: "Una opción discreta y cómoda. Alineadores transparentes que corrigen tu sonrisa sin que apenas se note.",
    descripcion_larga: "Los alineadores invisibles son férulas de plástico transparente que mueven los dientes de forma gradual y casi imperceptible. Se cambian cada 1–2 semanas. Se retiran para comer y cepillarse.",
    para_quien: "Para quien quiere discreción total. Especialmente popular entre adultos y profesionales.",
    duracion: "6–18 meses",
    precio_min: 2500, precio_max: 4500, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 11, updated_at: "",
    faq: [
      { pregunta: "¿Es tan eficaz como los brackets?", respuesta: "Para casos leves y moderados, la eficacia es comparable." },
      { pregunta: "¿Hay que llevarlos todo el día?", respuesta: "Se recomiendan 20–22 horas diarias. Se retiran solo para comer y cepillarse." },
    ],
  },
  {
    id: "3",
    slug: "implante-unitario",
    nombre: "Implante dental unitario",
    categoria: "implantes",
    descripcion_corta: "Recupera tus dientes perdidos con implantes dentales seguros, estables y con un aspecto natural. Para volver a sonreír sin preocuparte.",
    descripcion_larga: "Un implante dental es una raíz artificial de titanio que se coloca en el hueso. Sobre él se coloca una corona de porcelana personalizada. Es la solución más parecida a tener un diente natural.",
    para_quien: "Para cualquier persona que haya perdido uno o varios dientes y tenga suficiente hueso.",
    duracion: "3–6 meses (incluye cicatrización)",
    precio_min: 1200, precio_max: 2000, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 20, updated_at: "",
    faq: [
      { pregunta: "¿Duele la operación?", respuesta: "Se realiza con anestesia local. Durante la intervención no sientes dolor." },
      { pregunta: "¿Cuánto dura un implante?", respuesta: "Con una buena higiene, puede durar décadas o toda la vida." },
    ],
  },
  {
    id: "4",
    slug: "implantes-multiples",
    nombre: "Implantes múltiples",
    categoria: "implantes",
    descripcion_corta: "Cuando necesitas reponer varias piezas, los implantes múltiples son la solución más estable y natural.",
    descripcion_larga: "Si has perdido varios dientes, podemos valorar diferentes soluciones: implantes individuales para cada pieza, o estructuras que se apoyan en menos implantes (puentes sobre implantes).",
    para_quien: "Para quienes han perdido varios dientes y quieren una solución fija y duradera.",
    duracion: "Según planificación individual",
    precio_min: 2500, precio_max: 6000, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 21, updated_at: "", faq: [],
  },
  {
    id: "5",
    slug: "blanqueamiento-dental",
    nombre: "Blanqueamiento dental profesional",
    categoria: "estetica",
    descripcion_corta: "Mejoramos el aspecto de tu sonrisa con tratamientos estéticos como blanqueamientos. Natural, a tu medida.",
    descripcion_larga: "El blanqueamiento profesional aclara el tono de tus dientes de forma segura y controlada. En clínica usamos sistemas de luz y gel de alta concentración.",
    para_quien: "Para quien tiene los dientes manchados por café, té, tabaco o simplemente quiere un blanco más brillante.",
    duracion: "1 sesión (clínica) o 2–3 semanas (domiciliario)",
    precio_min: 200, precio_max: 400, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 30, updated_at: "",
    faq: [
      { pregunta: "¿Daña el esmalte?", respuesta: "El blanqueamiento profesional, bien indicado, no daña el esmalte." },
      { pregunta: "¿Funciona en dientes con coronas o carillas?", respuesta: "Solo actúa sobre dientes naturales." },
    ],
  },
  {
    id: "6",
    slug: "carillas-porcelana",
    nombre: "Carillas de porcelana",
    categoria: "estetica",
    descripcion_corta: "Transforma tu sonrisa de forma permanente con carillas ultrafinas de porcelana.",
    descripcion_larga: "Las carillas son láminas muy finas de porcelana que se adhieren a la cara visible del diente. Corrigen el color, la forma, el tamaño y pequeñas posiciones.",
    para_quien: "Para quien quiere un cambio estético significativo y duradero en su sonrisa.",
    duracion: "2–3 sesiones",
    precio_min: 600, precio_max: 1200, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 31, updated_at: "", faq: [],
  },
  {
    id: "7",
    slug: "composite-estetico",
    nombre: "Composite estético",
    categoria: "estetica",
    descripcion_corta: "Mejora tu sonrisa sin tocar el diente: el composite se aplica directamente sobre el esmalte.",
    descripcion_larga: "El composite es una resina de alta estética que el odontólogo modela directamente sobre el diente, sin necesidad de tallado ni laboratorio.",
    para_quien: "Ideal para corregir pequeñas fracturas, dientes separados o irregularidades leves.",
    duracion: "1 sesión por diente",
    precio_min: 150, precio_max: 350, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 32, updated_at: "", faq: [],
  },
  {
    id: "8",
    slug: "tratamiento-periodontal",
    nombre: "Tratamiento periodontal",
    categoria: "periodoncia",
    descripcion_corta: "Tratamos las enfermedades de las encías antes de que dañen tu sonrisa. Porque unas encías sanas son clave para mantener tus dientes.",
    descripcion_larga: "La periodontitis es la inflamación profunda de las encías. El tratamiento elimina las bacterias de las bolsas periodontales mediante raspado y alisado radicular.",
    para_quien: "Necesario cuando hay sangrado de encías persistente, encías retraídas, movilidad dental o mal aliento crónico.",
    duracion: "2–4 sesiones según severidad",
    precio_min: 200, precio_max: 600, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 40, updated_at: "", faq: [],
  },
  {
    id: "9",
    slug: "extraccion-muela-juicio",
    nombre: "Extracción de muela del juicio",
    categoria: "cirugia",
    descripcion_corta: "Cuando no queda otra opción, realizamos extracciones dentales seguras y con el menor impacto posible. Siempre con todas las garantías.",
    descripcion_larga: "Las muelas del juicio frecuentemente no tienen espacio para erupcionar correctamente, causando dolor, infecciones y daño a dientes vecinos. Se realiza bajo anestesia local.",
    para_quien: "Para quien tiene las muelas del juicio retenidas, semi-incluidas o que causan molestias.",
    duracion: "30–60 min por pieza",
    precio_min: 180, precio_max: 400, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 50, updated_at: "", faq: [],
  },
  {
    id: "10",
    slug: "cirugia-osea",
    nombre: "Cirugía de regeneración ósea",
    categoria: "cirugia",
    descripcion_corta: "Recuperamos el hueso perdido para que los implantes tengan la base que necesitan.",
    descripcion_larga: "Cuando hay pérdida de hueso, puede ser necesario regenerarlo antes de colocar implantes. Se utilizan membranas y materiales de relleno que estimulan la formación de nuevo hueso.",
    para_quien: "Indicado como paso previo a la implantología en casos con deficiencia ósea.",
    duracion: "Según extensión de la zona",
    precio_min: 400, precio_max: 1200, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 51, updated_at: "", faq: [],
  },
  {
    id: "11",
    slug: "revision-diagnostico",
    nombre: "Revisión y diagnóstico completo",
    categoria: "general",
    descripcion_corta: "Revisiones, higiene bucodental y tratamientos restauradores para mantener tu boca sana día a día. Es la base de todo buen cuidado dental.",
    descripcion_larga: "La primera visita incluye exploración completa, revisión radiológica si se precisa y un diagnóstico detallado en lenguaje claro. Sin sorpresas, sin presión.",
    para_quien: "Para cualquier persona que quiera saber cómo está su boca. Primera visita gratuita.",
    duracion: "30–45 minutos",
    precio_min: 0, precio_max: 0, unidad: "sesion",
    es_precio_real: false, visible: true, orden: 61, updated_at: "",
    faq: [{ pregunta: "¿La primera visita es gratuita?", respuesta: "Sí, la primera visita de valoración es sin coste y sin compromiso." }],
  },
  {
    id: "12",
    slug: "limpieza-bucal",
    nombre: "Limpieza dental profesional",
    categoria: "general",
    descripcion_corta: "La limpieza que marca la diferencia. Eliminamos el sarro y dejamos tu boca a punto.",
    descripcion_larga: "La limpieza profesional elimina el sarro y la placa que el cepillo no alcanza. También incluye pulido dental y fluorización si se indica. Se recomienda al menos una vez al año.",
    para_quien: "Para todo el mundo como mantenimiento preventivo.",
    duracion: "45–60 minutos",
    precio_min: 50, precio_max: 80, unidad: "sesion",
    es_precio_real: false, visible: true, orden: 62, updated_at: "",
    faq: [{ pregunta: "¿Con qué frecuencia debo hacerme una limpieza?", respuesta: "La recomendación general es una vez al año, o cada 6 meses si hay antecedentes de periodontitis." }],
  },
  {
    id: "13",
    slug: "empaste",
    nombre: "Empaste dental (composite)",
    categoria: "general",
    descripcion_corta: "Tratamos la caries y restauramos el diente con composite del color exacto de tus dientes.",
    descripcion_larga: "Cuando hay caries, extraemos el tejido dañado y rellenamos el espacio con un composite del color de tus dientes. El resultado es invisible, resistente y se termina en una sola visita.",
    para_quien: "Para cualquier persona con caries diagnosticada, de cualquier tamaño.",
    duracion: "30–60 minutos",
    precio_min: 50, precio_max: 120, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 63, updated_at: "",
    faq: [{ pregunta: "¿Se nota el empaste?", respuesta: "Con los composites actuales, el empaste queda del color exacto de tu diente." }],
  },
  {
    id: "14",
    slug: "endodoncia",
    nombre: "Endodoncia (tratamiento de conductos)",
    categoria: "general",
    descripcion_corta: "Salvamos el diente cuando la caries o una infección han llegado hasta el nervio.",
    descripcion_larga: "La endodoncia consiste en limpiar el interior del diente y sellarlo para evitar reinfecciones. Permite conservar el diente en la boca. Con la anestesia actual es un procedimiento cómodo.",
    para_quien: "Cuando hay infección profunda, dolor espontáneo nocturno o absceso dental.",
    duracion: "1–3 sesiones",
    precio_min: 200, precio_max: 450, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 64, updated_at: "", faq: [],
  },
  {
    id: "15",
    slug: "corona-dental",
    nombre: "Corona dental",
    categoria: "general",
    descripcion_corta: "Una funda que reconstruye y protege un diente muy dañado, devolviéndole función y estética.",
    descripcion_larga: "Una corona es una funda de cerámica que cubre completamente el diente para protegerlo cuando está muy desgastado, ha sufrido una endodoncia o está muy dañado por caries.",
    para_quien: "Para dientes fracturados, muy desgastados o tratados de endodoncia.",
    duracion: "2–3 sesiones",
    precio_min: 500, precio_max: 950, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 65, updated_at: "", faq: [],
  },
  {
    id: "16",
    slug: "revision-infantil",
    nombre: "Revisión infantil",
    categoria: "odontopediatria",
    descripcion_corta: "La primera visita de los peques: sin miedo, con paciencia y con mucho cariño.",
    descripcion_larga: "Somos especialmente cuidadosas con los más pequeños. La primera visita es siempre de conocernos y explorar sin prisa. Explicamos todo a los niños en su lenguaje.",
    para_quien: "Para niños desde la erupción de los primeros dientes de leche.",
    duracion: "30 minutos",
    precio_min: 0, precio_max: 40, unidad: "sesion",
    es_precio_real: false, visible: true, orden: 70, updated_at: "",
    faq: [{ pregunta: "¿A qué edad debo llevar a mi hijo/a por primera vez?", respuesta: "Recomendamos la primera visita alrededor del año de edad." }],
  },
  {
    id: "17",
    slug: "selladores-fisuras",
    nombre: "Selladores de fisuras",
    categoria: "odontopediatria",
    descripcion_corta: "Protección preventiva para los dientes definitivos de los niños: evitamos la caries antes de que llegue.",
    descripcion_larga: "Los selladores son una resina que se aplica en las fisuras de los molares definitivos recién erupcionados. Es un procedimiento rápido, sin anestesia y muy eficaz para prevenir caries.",
    para_quien: "Para niños de 6–12 años con molares definitivos recién erupcionados.",
    duracion: "15–20 min por cuadrante",
    precio_min: 30, precio_max: 60, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 71, updated_at: "", faq: [],
  },
  {
    id: "18",
    slug: "ortodoncia-infantil",
    nombre: "Ortodoncia interceptiva infantil",
    categoria: "odontopediatria",
    descripcion_corta: "Corregimos a tiempo los problemas que, si se tratan pronto, se resuelven con mucha más facilidad.",
    descripcion_larga: "La ortodoncia interceptiva actúa sobre la mandíbula y los maxilares en crecimiento para corregir discrepancias antes de que se agraven.",
    para_quien: "Para niños entre 6 y 12 años con problemas de mordida, paladar estrecho o apiñamiento severo.",
    duracion: "12–24 meses",
    precio_min: 800, precio_max: 1800, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 72, updated_at: "", faq: [],
  },
  {
    id: "19",
    slug: "autotrasplante-dental",
    nombre: "Autotrasplante dental",
    categoria: "implantes",
    descripcion_corta: "Utilizamos una pieza dental tuya para sustituir otra que no puede conservarse. Una solución innovadora y eficaz.",
    descripcion_larga: "El autotrasplante dental consiste en trasladar un diente propio desde su posición original a otra donde se ha perdido o no puede conservarse. Es una alternativa biológica y duradera a los implantes convencionales, especialmente indicada en pacientes jóvenes.",
    para_quien: "Para pacientes con pérdida dental en los que exista un diente donante adecuado, generalmente muelas del juicio.",
    duracion: "Según planificación individual",
    precio_min: 800, precio_max: 1800, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 22, updated_at: "", faq: [],
  },
  {
    id: "20",
    slug: "diseno-digital-sonrisa",
    nombre: "Diseño digital de la sonrisa (DSD)",
    categoria: "estetica",
    descripcion_corta: "Planificamos tu sonrisa ideal de forma digital antes del tratamiento. Así puedes ver el resultado antes de tomar la decisión.",
    descripcion_larga: "El Diseño Digital de la Sonrisa (DSD) es una herramienta de planificación que permite visualizar el resultado estético antes de iniciar cualquier tratamiento. Con fotografías y software especializado, simulamos cómo quedarán tus dientes.",
    para_quien: "Para cualquier persona que quiera cambiar su sonrisa y desee ver el resultado esperado antes de comprometerse.",
    duracion: "1 sesión de planificación",
    precio_min: 0, precio_max: 0, unidad: "sesion",
    es_precio_real: false, visible: true, orden: 33, updated_at: "", faq: [],
  },
  {
    id: "21",
    slug: "disyuncion-palatina",
    nombre: "Disyunción palatina",
    categoria: "ortodoncia",
    descripcion_corta: "Tratamiento avanzado que corrige la estructura del maxilar para mejorar la respiración, la funcionalidad y la estabilidad de la sonrisa con resultados duraderos.",
    descripcion_larga: "La disyunción palatina es un tratamiento ortodóncico que amplía el paladar mediante un dispositivo expansor. Corrige el paladar estrecho, mejora la respiración nasal y crea espacio para que los dientes se alineen correctamente.",
    para_quien: "Para pacientes con paladar estrecho, respiración bucal o problemas de mordida cruzada posterior.",
    duracion: "3–6 meses",
    precio_min: 800, precio_max: 1500, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 12, updated_at: "", faq: [],
  },
  {
    id: "22",
    slug: "microimplantes-dentales",
    nombre: "Microimplantes dentales",
    categoria: "implantes",
    descripcion_corta: "Soluciones mínimamente invasivas para mejorar la estabilidad de prótesis o sustituir piezas dentales en casos específicos. Comodidad y funcionalidad desde el primer momento.",
    descripcion_larga: "Los microimplantes dentales son pequeños implantes de titanio que se colocan de forma mínimamente invasiva. Se usan como anclaje en ortodoncia o como soporte de prótesis en casos donde los implantes convencionales no son viables.",
    para_quien: "Para pacientes que necesitan anclaje ortodóncico adicional o soporte protésico con poco hueso disponible.",
    duracion: "1 sesión de colocación",
    precio_min: 300, precio_max: 700, unidad: "pieza",
    es_precio_real: false, visible: true, orden: 23, updated_at: "", faq: [],
  },
  {
    id: "23",
    slug: "cirugia-periodontal",
    nombre: "Cirugía periodontal",
    categoria: "periodoncia",
    descripcion_corta: "Tratamientos avanzados para eliminar la infección en las encías y frenar su avance. Protegemos la base de tu sonrisa para mantener tus dientes a largo plazo.",
    descripcion_larga: "La cirugía periodontal se indica cuando el tratamiento no quirúrgico no es suficiente para controlar la enfermedad de las encías. Permite acceder a zonas profundas para eliminar la infección y, en algunos casos, regenerar tejido óseo perdido.",
    para_quien: "Para pacientes con periodontitis avanzada que no responde al tratamiento convencional.",
    duracion: "1–2 sesiones según extensión",
    precio_min: 500, precio_max: 1500, unidad: "tratamiento",
    es_precio_real: false, visible: true, orden: 41, updated_at: "", faq: [],
  },
];
